### PR TITLE
matrix: add Fedora45 and fix OpenSSL 4 build errors in TLS/crypto code

### LINKED ISSUE #2743: build with OpenSSL 4.0 fails
### Bareos component version

25.1.0

### Steps to reproduce

Simple compile it under Fedora 45 (raw)

### Expected results

Working build

### Actual results

gcc error:
```
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:261:21: error: invalid conversion from ‘const X509_EXTENSION*’ {aka ‘const X509_extension_st*’} to ‘X509_EXTENSION*’ {aka ‘X509_extension_st*’} [-fpermissive]
  261 |   ext = X509_get_ext(cert, i);
      |         ~~~~~~~~~~~~^~~~~~~~~
      |                     |
      |                     const X509_EXTENSION* {aka const X509_extension_st*}
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:266:48: error: invalid use of incomplete type ‘const ASN1_OCTET_STRING’ {aka ‘const struct asn1_string_st’}
  266 |   ext_value_data = X509_EXTENSION_get_data(ext)->data;
      |                                                ^~
In file included from /usr/include/openssl/err.h:30,
                 from /builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:34:
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:273:60: error: invalid use of incomplete type ‘const ASN1_OCTET_STRING’ {aka ‘const struct asn1_string_st’}
  273 |         NULL, &ext_value_data, X509_EXTENSION_get_data(ext)->length,
      |                                                            ^~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:280:60: error: invalid use of incomplete type ‘const ASN1_OCTET_STRING’ {aka ‘const struct asn1_string_st’}
  280 |         NULL, &ext_value_data, X509_EXTENSION_get_data(ext)->length);
      |                                                            ^~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc: In function ‘crypto_error_t CryptoSignVerify(SIGNATURE*, X509_KEYPAIR*, DIGEST*)’:
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:149:37: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  149 | #define M_ASN1_STRING_length(x) ((x)->length)
      |                                     ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:701:16: note: in expansion of macro ‘M_ASN1_STRING_length’
  701 |       sigLen = M_ASN1_STRING_length(si->signature);
      |                ^~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:150:35: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  150 | #define M_ASN1_STRING_data(x) ((x)->data)
      |                                   ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:702:17: note: in expansion of macro ‘M_ASN1_STRING_data’
  702 |       sigData = M_ASN1_STRING_data(si->signature);
      |                 ^~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc: In function ‘crypto_error_t CryptoSessionDecode(const uint8_t*, uint32_t, alist<X509_Keypair*>*, CRYPTO_SESSION**)’:
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:150:35: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  150 | #define M_ASN1_STRING_data(x) ((x)->data)
      |                                   ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:1174:30: note: in expansion of macro ‘M_ASN1_STRING_data’
 1174 |             cs->session_key, M_ASN1_STRING_data(ri->encryptedKey),
      |                              ^~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:149:37: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  149 | #define M_ASN1_STRING_length(x) ((x)->length)
      |                                     ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:1175:13: note: in expansion of macro ‘M_ASN1_STRING_length’
 1175 |             M_ASN1_STRING_length(ri->encryptedKey), keypair->privkey);
      |             ^~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc: In function ‘CIPHER_CONTEXT* crypto_cipher_new(CRYPTO_SESSION*, bool, uint32_t*)’:
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:149:37: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  149 | #define M_ASN1_STRING_length(x) ((x)->length)
      |                                     ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:1252:35: note: in expansion of macro ‘M_ASN1_STRING_length’
 1252 |   if (EVP_CIPHER_iv_length(ec) != M_ASN1_STRING_length(cs->cryptoData->iv)) {
      |                                   ^~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:150:35: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  150 | #define M_ASN1_STRING_data(x) ((x)->data)
      |                                   ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:1259:26: note: in expansion of macro ‘M_ASN1_STRING_data’
 1259 |                          M_ASN1_STRING_data(cs->cryptoData->iv), -1)) {
      |                          ^~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
```

### Environment

```markdown
- OS: `Fedora-45`
- component: openssl 4.0.1
```

### Relevant log output

```shell

```

### Relevant traces output

```shell

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pstorz**
OpenSSL 4 made `ASN1_STRING`, `X509_EXTENSION` and `X509_NAME` internals opaque and marked `X509_NAME_get_text_by_NID` deprecated. Replace direct struct field access and the deprecated call with the public accessor functions (`ASN1_STRING_get0_data`/`length`, `X509_NAME_get_entry`, `X509_NAME_ENTRY_get_data`), keeping compatibility with OpenSSL >= 1.1.1.

Also const-correct the `X509_NAME` locals in the
certificate-generation test helper, since
`X509_get_subject_name()` now always returns a const pointer.

TODO: 
- [x] Add Fedora 45 as build target

#### Please check

- [x] Short description and the purpose of this PR is present _above this paragraph_
- [x] Your name is present in the AUTHORS file (optional)

If you have any questions or problems, please give a comment in the PR.

### Helpful documentation and best practices

- [Git Workflow](https://docs.bareos.org/DeveloperGuide/gitworkflow.html)
- [Automatic Sourcecode Formatting](https://docs.bareos.org/DeveloperGuide/generaldevel.html#automatic-sourcecode-formatting)
- [Check your commit messages](https://docs.bareos.org/DeveloperGuide/gitworkflow.html#commits)
- [Boy Scout Rule](https://docs.bareos.org/DeveloperGuide/generaldevel.html#boy-scout-rule)

### Checklist for the _reviewer_ of the PR (will be processed by the Bareos team)
Make sure you check/merge the PR using `devtools/pr-tool` to have some simple automated checks run and a proper changelog record added.

##### General
- [x] Is the PR title usable as CHANGELOG entry?
- [x] Purpose of the PR is understood
- [x] Commit descriptions are understandable and well formatted
- [x] Required backport PRs have been created
- If a release should wait for this PR to be finished, set that release's milestone.

##### Source code quality
- [x] Source code changes are understandable
- [x] Variable and function names are meaningful
- [x] Code comments are correct (logically and spelling)
- [x] Required documentation changes are present and part of the PR

##### Tests
- [x] Decision taken that a test is required (if not, then remove this paragraph)
- [x] The choice of the type of test (unit test or systemtest) is reasonable
- [x] Testname matches exactly what is being tested
- [x] On a fail, output of the test leads quickly to the origin of the fault

### CODE REVIEW

File: core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py [hunk 1]
```diff
@@ -297,14 +297,22 @@ def plugin_io_open(self, IOP):
...
-            return bRC_OK
         else:
+            try:
+                is_fifo = stat.S_ISFIFO(os.stat(self.FNAME).st_mode)
+            except FileNotFoundError:
+                bareosfd.JobMessage(
+                    M_WARNING,
+                    "File %s disappeared while being opened\n" % self.FNAME,
+                )
+                return bRC_Skip
```
Comment (sebsura) [inline core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py:308]: This does not make sense to me.  open can also be called to write a file.  Why would we "skip" the file, if it does not exist yet ? Previously we only returned Error/OK; is the caller equipped to handle SKIP ?

Comment (sebsura) [reply core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py:308]:
```
                if not os.path.exists(dirname):
                    bareosfd.DebugMessage(
                        100,
                        "Directory %s does not exist, creating it now\n" % (dirname),
                    )
                    os.makedirs(dirname)
```
Can this even be hit anymore ? (See below) Its possible that I am missing something here.

Comment (sebsura) [reply core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py:308]: Commit cf7bf0fd0a689e74d63ddea691fcb7d6080e01a8 fixes this, It should be marked as a fixup commit.

File: core/src/lib/tls/openssl/impl.cc [hunk 2]
```diff
@@ -878,10 +892,11 @@ bool TlsOpenSsl::TlsPostconnectVerifyHost(JobControlRecord* jcr,
   // Check subjectAltName extensions first
   if ((extensions = X509_get_ext_count(cert)) > 0) {
     for (i = 0; i < extensions; i++) {
-      X509_EXTENSION* ext;
       const char* extname;
 
-      ext = X509_get_ext(cert, i);
+      /* auto: X509_get_ext() returns a non-const pointer on OpenSSL < 3.0
+       * and a const pointer on OpenSSL >= 4.0 */
```
Comment (sebsura) [inline core/src/lib/tls/openssl/impl.cc:898]: These comments are unnecessary.  If its clear what it returns, you can always use auto.  If its not clear, you can always use `const X509_EXTENSION*`.

File: core/src/lib/tls/openssl/impl.cc [hunk 3]
```diff
@@ -893,17 +908,23 @@ bool TlsOpenSsl::TlsPostconnectVerifyHost(JobControlRecord* jcr,
...
         } else {
           /* Old style ASN1
            * Decode ASN1 item in data */
-          extstr = method->d2i(NULL, &ext_value_data,
-                               X509_EXTENSION_get_data(ext)->length);
+          extstr = method->d2i(
+              NULL, &ext_value_data,
+              ASN1_STRING_length(
+                  reinterpret_cast<const ASN1_STRING*>(ext_value)));
         }
```
Comment (sebsura) [inline core/src/lib/tls/openssl/impl.cc:928]: Lets not do this ourselves.  openssl comes with this function:
```
void *X509V3_EXT_d2i(const X509_EXTENSION *ext)
{
    const X509V3_EXT_METHOD *method;
    const unsigned char *p;
    const ASN1_STRING *extvalue;
    int extlen;

    if ((method = X509V3_EXT_get(ext)) == NULL)
        return NULL;
    extvalue = X509_EXTENSION_get_data(ext);
    p = ASN1_STRING_get0_data(extvalue);
    extlen = ASN1_STRING_length(extvalue);
    if (method->it)
        return ASN1_item_d2i(NULL, &p, extlen, ASN1_ITEM_ptr(method->it));
    return method->d2i(NULL, &p, extlen);
}
```

As you can see, it does exactly what we did, so you can just say:
```
  auto* ext = X509_get_ext(cert, i);
  return static_cast<ASN1_OCTET_STRING*>(X509V3_EXT_d2i(ext));
```

File: core/src/lib/tls/openssl/impl.cc [hunk 4]
```diff
@@ -142,6 +142,18 @@ class TlsOpenSsl : public Tls {
 constexpr std::string_view tls_default_ciphers_{
     "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH"};
 
+std::optional<std::string> GetCommonName(const X509_NAME* subject, int index)
+{
+  const X509_NAME_ENTRY* entry = X509_NAME_get_entry(subject, index);
+  const ASN1_STRING* name = X509_NAME_ENTRY_get_data(entry);
```
Comment (sebsura) [inline core/src/lib/tls/openssl/impl.cc:148]: we need null checks here!

File: core/src/lib/tls/openssl/impl.cc [hunk 5]
```diff
@@ -142,6 +142,18 @@ class TlsOpenSsl : public Tls {
...
+  const unsigned char* data = ASN1_STRING_get0_data(name);
```
Comment (sebsura) [inline core/src/lib/tls/openssl/impl.cc:149]: asn1 strings are not guaranteed to be utf8, we should probably use ASN1_STRING_to_UTF8 here

File: core/src/lib/crypto_openssl.cc [hunk 6]
```diff
@@ -146,8 +146,8 @@ IGNORE_UNREFERENCED_FUNCTION_OFF
   (ASN1_OCTET_STRING*)ASN1_STRING_dup((const ASN1_STRING*)a)
 #define M_ASN1_OCTET_STRING_set(a, b, c) ASN1_STRING_set((ASN1_STRING*)a, b, c)
 
-#define M_ASN1_STRING_length(x) ((x)->length)
-#define M_ASN1_STRING_data(x) ((x)->data)
+#define M_ASN1_STRING_length(x) ASN1_STRING_length((const ASN1_STRING*)x)
+#define M_ASN1_STRING_data(x) ASN1_STRING_get0_data((const ASN1_STRING*)x)
```
Comment (sebsura) [inline core/src/lib/crypto_openssl.cc:150]: Lets just gete rid of these macros

File: core/src/tests/test_bsock.cc [hunk 7]
```diff
@@ -262,19 +262,21 @@ X509Ptr GenerateCertificate(EVP_PKEY* subject_key,
...
+  auto* subject = X509_get_subject_name(cert.get());
   if (!subject
       || X509_NAME_add_entry_by_txt(
-             subject, "CN", MBSTRING_ASC,
+             const_cast<X509_NAME*>(subject), "CN", MBSTRING_ASC,
              reinterpret_cast<const unsigned char*>(common_name.data()), -1, -1,
              0)
              != 1) {
     *error = "Could not set certificate subject: " + GetOpenSslError();
     return {nullptr, X509_free};
```
Comment (sebsura) [inline core/src/tests/test_bsock.cc]: if the api returns a const pointer, we are not meant to modify it.  Instead we should just create a new one (X509_NAME_new()) and then set it in the certificate (X509_set_subject_name).

File: core/src/lib/tls/openssl/impl.cc [hunk 8]
```diff
@@ -811,23 +823,28 @@ bool TlsOpenSsl::TlsPostconnectVerifyCn(
...
-    char data[256]; /* nullterminated by X509_NAME_get_text_by_NID */
-    if (X509_NAME_get_text_by_NID(subject, NID_commonName, data, sizeof(data))
-        > 0) {
-      const std::string_view d(data);
-      for (const std::string& cn : verify_list) {
-        Dmsg2(120, "comparing CNs: cert-cn=%s, allowed-cn=%s\n", data,
-              cn.c_str());
-        if (d.compare(cn) == 0) { auth_success = true; }
+  /* auto: X509_get_subject_name() returns a non-const pointer on
+   * OpenSSL < 4.0 and a const pointer on OpenSSL >= 4.0 */
```
Comment (sebsura) [inline core/src/lib/tls/openssl/impl.cc:834]: remove

File: core/src/lib/tls/openssl/impl.cc [hunk 9]
```diff
@@ -811,23 +823,28 @@ bool TlsOpenSsl::TlsPostconnectVerifyCn(
...
+  auto* subject = X509_get_subject_name(cert);
+  if (subject != NULL) {
+    const int common_name_index
+        = X509_NAME_get_index_by_NID(subject, NID_commonName, -1);
```
Comment (sebsura) [inline core/src/lib/tls/openssl/impl.cc:838]: This should probably be part of GetCommonName (unless a currenct call site gets the index a different way)

File: core/src/lib/crypto_openssl.cc [hunk 10]
```diff
@@ -258,26 +257,31 @@ static ASN1_OCTET_STRING* openssl_cert_keyid(X509* cert)
...
+  /* auto: X509_get_ext() returns a non-const pointer on OpenSSL < 3.0
+   * and a const pointer on OpenSSL >= 4.0 */
+  auto* ext = X509_get_ext(cert, i);
 
   /* Get x509 extension method structure */
   if (!(method = X509V3_EXT_get(ext))) { return NULL; }
 
-  ext_value_data = X509_EXTENSION_get_data(ext)->data;
+  auto* ext_value = X509_EXTENSION_get_data(ext);
+  ext_value_data = ASN1_STRING_get0_data((const ASN1_STRING*)ext_value);
```
Comment (sebsura) [inline core/src/lib/crypto_openssl.cc:268]: same as above, use the openssl method for this.

**Review by sebsura — CHANGES_REQUESTED** [review]
Coderabbit also found some things.

File: core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py [hunk 11]
```diff
@@ -297,14 +297,22 @@ def plugin_io_open(self, IOP):
...
-            self.fileType = "FT_FIFO"
-            bareosfd.DebugMessage(
-                100,
-                "Did not open file %s of type %s\n" % (self.FNAME, self.fileType),
-            )
-            return bRC_OK
         else:
+            try:
+                is_fifo = stat.S_ISFIFO(os.stat(self.FNAME).st_mode)
+            except FileNotFoundError:
```
[the remark this answers is not in the document]
Comment (pstorz) [reply core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py]: Fixed by cf7bf0f

File: core/src/lib/tls/openssl/impl.cc (hunk 4 above)
Comment (pstorz) [reply core/src/lib/tls/openssl/impl.cc:165]: Were added

File: core/src/lib/tls/openssl/impl.cc (hunk 5 above)
Comment (pstorz) [reply core/src/lib/tls/openssl/impl.cc]: Addressed and Test was added

File: core/src/lib/crypto_openssl.cc (hunk 6 above)
Comment (pstorz) [reply core/src/lib/crypto_openssl.cc]: Done

File: core/src/tests/test_bsock.cc [hunk 12]
```diff
@@ -265,11 +265,12 @@ X509Ptr GenerateCertificate(EVP_PKEY* subject_key,
...
   if (!subject
-      || X509_NAME_add_entry_by_txt(
-             subject.get(), "CN", MBSTRING_ASC,
-             reinterpret_cast<const unsigned char*>(common_name.data()), -1, -1,
-             0)
-             != 1
+      || (!common_name.empty()
+          && X509_NAME_add_entry_by_txt(
+                 subject.get(), "CN", MBSTRING_UTF8,
+                 reinterpret_cast<const unsigned char*>(common_name.data()), -1,
```
Comment (sebsura) [inline core/src/tests/test_bsock.cc]: The second parameter of this function takes in a length.  It probably makes sense to specify it considering we take in a string_view.

File: core/src/lib/tls/openssl/impl.cc
Comment (sebsura) [inline core/src/lib/tls/openssl/impl.cc]: It probably makes sense to just ask openssl for the alternate names.  According the an LLM it is done by simply doing:

```
GENERAL_NAMES *sans =
    X509_get_ext_d2i(cert, NID_subject_alt_name, NULL, NULL);

if (sans) {
    int count = sk_GENERAL_NAME_num(sans);

    for (int i = 0; i < count; i++) {
        GENERAL_NAME *name = sk_GENERAL_NAME_value(sans, i);

        if (name->type == GEN_DNS) {
            ASN1_IA5STRING *dns = name->d.dNSName;

            const unsigned char *data = ASN1_STRING_get0_data(dns);
            int len = ASN1_STRING_length(dns);

            printf("DNS SAN: %.*s\n", len, data);
        }
    }

    GENERAL_NAMES_free(sans);
}
```

Ill try to check how the check_hosts() function does it in openssl proper.

File: core/src/tests/test_bsock.cc [hunk 13]
```diff
@@ -804,6 +819,74 @@ TEST(bsock, auth_fails_with_revoked_tls_cert)
   EXPECT_FALSE(future.get());
 }
 
+TEST(bsock, auth_works_with_utf8_tls_common_name)
+{
+  // Bäreos Client
+  constexpr std::string_view client_common_name{"B\xC3\xA4reos Client"};
```
Comment (sebsura) [inline core/src/tests/test_bsock.cc]: Maybe its possible to use u8"Bäreos" for this, otherwise we should expand the comment to say what its doing, i.e. "test with Bäreos Client"

File: core/src/tests/test_bsock.cc [hunk 14]
```diff
@@ -808,6 +819,74 @@ TEST(bsock, auth_fails_with_revoked_tls_cert)
   EXPECT_FALSE(future.get());
 }
 
+TEST(bsock, auth_works_with_utf8_tls_common_name)
```
Comment (sebsura) [inline core/src/tests/test_bsock.cc:905]: A test regarding included 0 is missing.

File: core/src/tests/test_bsock.cc [hunk 15]
```diff
@@ -265,11 +265,12 @@ X509Ptr GenerateCertificate(EVP_PKEY* subject_key,
 
   X509NamePtr subject{X509_NAME_new()};
   if (!subject
-      || X509_NAME_add_entry_by_txt(
-             subject.get(), "CN", MBSTRING_ASC,
-             reinterpret_cast<const unsigned char*>(common_name.data()), -1, -1,
-             0)
-             != 1
+      || (!common_name.empty()
```
Comment (sebsura) [inline core/src/tests/test_bsock.cc:272]: Why do we now check for empty names ? Is it an error to call the function with an empty name ?

File: core/src/lib/tls/openssl/impl.cc [hunk 16]
```diff
@@ -142,16 +142,40 @@ class TlsOpenSsl : public Tls {
...
+  const ASN1_STRING* name = X509_NAME_ENTRY_get_data(entry);
+  if (!name) { return std::nullopt; }
+
+  unsigned char* raw_utf8_data = nullptr;
+  const int length = ASN1_STRING_to_UTF8(&raw_utf8_data, name);
+  using Utf8DataPtr
+      = std::unique_ptr<unsigned char, decltype([](unsigned char* data) {
+                          OPENSSL_free(data);
+                        })>;
+  Utf8DataPtr utf8_data(raw_utf8_data);
```
Comment (sebsura) [inline core/src/lib/tls/openssl/impl.cc]: Since we are using {} for value & CommonName, we should probably also use it here, but its just a minor nitpick.

**Review by sebsura — CHANGES_REQUESTED** [review]

File: core/src/tests/test_bsock.cc (hunk 15 above)
Comment (pstorz) [reply core/src/tests/test_bsock.cc:272]: The `!common_name.empty()` check allows `GenerateCertificate()` to intentionally generate test certificates without a `commonName` attribute in the subject (e.g. for `bsock.auth_fails_with_missing_tls_common_name`), without attempting to add an empty CN entry.

**Review by sebsura — APPROVED** [review]
Thanks for the awesome work!

**Comment by tuxmaster** [comment]
Are there any plans to release the patch for the 25 series as well?
