### ISSUE TITLE
build with OpenSSL 4.0 fails

### ISSUE THREAD

**Issue by tuxmaster** [bareos/bareos#2743]
### Bareos component version

25.1.0

### Steps to reproduce

Simple compile it under Fedora 45 (raw)

### Expected results

Working build

### Actual results

gcc error:
```
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:261:21: error: invalid conversion from ‘const X509_EXTENSION*’ {aka ‘const X509_extension_st*’} to ‘X509_EXTENSION*’ {aka ‘X509_extension_st*’} [-fpermissive]
  261 |   ext = X509_get_ext(cert, i);
      |         ~~~~~~~~~~~~^~~~~~~~~
      |                     |
      |                     const X509_EXTENSION* {aka const X509_extension_st*}
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:266:48: error: invalid use of incomplete type ‘const ASN1_OCTET_STRING’ {aka ‘const struct asn1_string_st’}
  266 |   ext_value_data = X509_EXTENSION_get_data(ext)->data;
      |                                                ^~
In file included from /usr/include/openssl/err.h:30,
                 from /builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:34:
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:273:60: error: invalid use of incomplete type ‘const ASN1_OCTET_STRING’ {aka ‘const struct asn1_string_st’}
  273 |         NULL, &ext_value_data, X509_EXTENSION_get_data(ext)->length,
      |                                                            ^~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:280:60: error: invalid use of incomplete type ‘const ASN1_OCTET_STRING’ {aka ‘const struct asn1_string_st’}
  280 |         NULL, &ext_value_data, X509_EXTENSION_get_data(ext)->length);
      |                                                            ^~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc: In function ‘crypto_error_t CryptoSignVerify(SIGNATURE*, X509_KEYPAIR*, DIGEST*)’:
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:149:37: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  149 | #define M_ASN1_STRING_length(x) ((x)->length)
      |                                     ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:701:16: note: in expansion of macro ‘M_ASN1_STRING_length’
  701 |       sigLen = M_ASN1_STRING_length(si->signature);
      |                ^~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:150:35: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  150 | #define M_ASN1_STRING_data(x) ((x)->data)
      |                                   ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:702:17: note: in expansion of macro ‘M_ASN1_STRING_data’
  702 |       sigData = M_ASN1_STRING_data(si->signature);
      |                 ^~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc: In function ‘crypto_error_t CryptoSessionDecode(const uint8_t*, uint32_t, alist<X509_Keypair*>*, CRYPTO_SESSION**)’:
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:150:35: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  150 | #define M_ASN1_STRING_data(x) ((x)->data)
      |                                   ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:1174:30: note: in expansion of macro ‘M_ASN1_STRING_data’
 1174 |             cs->session_key, M_ASN1_STRING_data(ri->encryptedKey),
      |                              ^~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:149:37: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  149 | #define M_ASN1_STRING_length(x) ((x)->length)
      |                                     ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:1175:13: note: in expansion of macro ‘M_ASN1_STRING_length’
 1175 |             M_ASN1_STRING_length(ri->encryptedKey), keypair->privkey);
      |             ^~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc: In function ‘CIPHER_CONTEXT* crypto_cipher_new(CRYPTO_SESSION*, bool, uint32_t*)’:
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:149:37: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  149 | #define M_ASN1_STRING_length(x) ((x)->length)
      |                                     ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:1252:35: note: in expansion of macro ‘M_ASN1_STRING_length’
 1252 |   if (EVP_CIPHER_iv_length(ec) != M_ASN1_STRING_length(cs->cryptoData->iv)) {
      |                                   ^~~~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:150:35: error: invalid use of incomplete type ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
  150 | #define M_ASN1_STRING_data(x) ((x)->data)
      |                                   ^~
/builddir/build/BUILD/bareos-25.1.0-build/bareos-Release-25.1.0/core/src/lib/crypto_openssl.cc:1259:26: note: in expansion of macro ‘M_ASN1_STRING_data’
 1259 |                          M_ASN1_STRING_data(cs->cryptoData->iv), -1)) {
      |                          ^~~~~~~~~~~~~~~~~~
/usr/include/openssl/types.h:57:16: note: forward declaration of ‘ASN1_OCTET_STRING’ {aka ‘struct asn1_string_st’}
   57 | typedef struct asn1_string_st ASN1_INTEGER;
      |                ^~~~~~~~~~~~~~
```

### Environment

```markdown
- OS: `Fedora-45`
- component: openssl 4.0.1
```

### Relevant log output

```shell

```

### Relevant traces output

```shell

```

**Comment by arogge** [comment]
That looks a lot more than an OpenSSL 4 issue than a GCC 16 issue.

**Comment by tuxmaster** [comment]
It can be, because I don't know the internals of OpenSSL 4. On 3.5 all are fine.

**Comment by bruno-at-bareos** [comment]
Bareos build fine with gcc 16.1.1 on openSUSE Tumbleweed.
Didn't have openssl 4.
