### ISSUE TITLE
New 23.0.3 NVRAM changes to VMware plugin break on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by TotalGriffLock** [bareos/bareos#1760]
### Bareos component version

bareos-fd --version     `23.0.3~pre63.bb6c03acf`
bareos-dir --version    `23.0.3~pre63.bb6c03acf`
bareos-sd --version     `23.0.3~pre63.bb6c03acf`
bconsole --version       `23.0.3~pre63.bb6c03acf`

### Steps to reproduce

1. Have Ubuntu 20.04 LTS installed with the OS supplied release of urllib3
2. Update to BareOS 23.0.3
3. Try to back up a VM from VCenter

### Expected results

Backup succeeds, as it did prior to the upgrade to 23.0.3

### Actual results

```
JobId 31832: Fatal error: bareosfd: Traceback (most recent call last):
File "/usr/lib/bareos/plugins/BareosFdWrapper.py", line 59, in handle_plugin_event
return bareos_fd_plugin_object.handle_plugin_event(event)
File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 1057, in handle_plugin_event
return self.start_backup_job()
File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 497, in start_backup_job
return self.vadp.prepare_vm_backup()
File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 1492, in prepare_vm_backup
if self.get_vm_nvram():
File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 3226, in get_vm_nvram
self.vm_nvram_content = self.retrieve_file_content_from_datastore(
File "/usr/lib/bareos/plugins/bareos-fd-vmware.py", line 3310, in retrieve_file_content_from_datastore
retries = urllib3.util.Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

### Environment

```markdown
- OS: `NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`
- component:
python3-urllib3/focal-updates,focal-security,now 1.25.8-2ubuntu0.3 all [installed]
```

### Anything else?

I resolved this issue in my instance by doing a do-release-upgrade. Other users may find the info contained within this issue useful. The version of urllib3 available via apt in Ubuntu 20.04 LTS is from 2020.

**Comment by TotalGriffLock** [comment]
In addition to the above, and I know that you do not cover VMware permissions in your docs but this may be useful info for other users, I also had to give the bareos user in vcenter an additional permission to enable nvram backup:

Datastore\Browse datastore

**Comment by sduehr** [comment]
Thanks for reporting this and the hint about permissions.
So did you find a workaround to get the plugin to work on Ubuntu 20.04 LTS?
Like for example is it possible to uninstall the python3-urllib3 package and install a current version using pip?

**Comment by TotalGriffLock** [comment]
As this server was already overdue a distribution upgrade that was my go-to solution, I'm afraid I did not try any workarounds.

**Comment by karlism** [comment]
I'm also seeing this issue on Oracle Linux 8:
```
hostname JobId 457370: Fatal error: bareosfd: Traceback (most recent call last):
File "/usr/lib64/bareos/plugins/BareosFdWrapper.py", line 59, in handle_plugin_event
return bareos_fd_plugin_object.handle_plugin_event(event)
File "/usr/lib64/bareos/plugins/bareos-fd-vmware.py", line 1057, in handle_plugin_event
return self.start_backup_job()
File "/usr/lib64/bareos/plugins/bareos-fd-vmware.py", line 497, in start_backup_job
return self.vadp.prepare_vm_backup()
File "/usr/lib64/bareos/plugins/bareos-fd-vmware.py", line 1492, in prepare_vm_backup
if self.get_vm_nvram():
File "/usr/lib64/bareos/plugins/bareos-fd-vmware.py", line 3227, in get_vm_nvram
vm_nvram_datastore_name, vm_nvram_file_path
File "/usr/lib64/bareos/plugins/bareos-fd-vmware.py", line 3314, in retrieve_file_content_from_datastore
allowed_methods={"GET"},
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```


```
# cat /etc/os-release 
NAME="Oracle Linux Server"
VERSION="8.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:8:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.8
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.8

# dnf list installed | grep -e bareos -e urllib
bareos-common.x86_64                              23.0.3~pre87.e086dcd6e-80.el8                               @bareos-22     
bareos-filedaemon.x86_64                          23.0.3~pre87.e086dcd6e-80.el8                               @bareos-22     
bareos-filedaemon-python-plugins-common.x86_64    23.0.3~pre87.e086dcd6e-80.el8                               @bareos-22     
bareos-filedaemon-python3-plugin.x86_64           23.0.3~pre87.e086dcd6e-80.el8                               @bareos-22     
bareos-vadp-dumper.x86_64                         23.0.3~pre87.e086dcd6e-80.el8                               @bareos-22     
bareos-vmware-plugin.x86_64                       23.0.3~pre87.e086dcd6e-80.el8                               @bareos-22     
bareos-vmware-vix-disklib.x86_64                  8.0.2_22388865-1.el8                                        @bareos-22     
python3-urllib3.noarch                            1.24.2-5.0.1.el8                                            @ol-latest     

# pip3 list | grep urllib
urllib3 (1.24.2)
```

I've also tried taking backup with vCenter administrator user and it failed so I do not think it is vCenter account permission issue.

**Comment by sduehr** [comment]
Looks like the parameter was named `method_whitelist` in the 1.x version of urllib3, see
https://urllib3.readthedocs.io/en/1.26.8/reference/urllib3.util.html

Ideas of how the Python code can handle both versions are welcome.

The Python code I'm talking about is
https://github.com/bareos/bareos/blob/master/core/src/plugins/filed/python/vmware/bareos-fd-vmware.py#L3310-L3315
and
https://github.com/bareos/bareos/blob/master/core/src/plugins/filed/python/vmware/bareos-fd-vmware.py#L3376-L3381

**Comment by TotalGriffLock** [comment]
Perhaps an if statement based around urllib.request.__version__ would suffice

**Comment by sduehr** [comment]
Thanks, yes, using `__version__` should work.
Alternative: `hasattr(urllib3.util.Retry, 'DEFAULT_ALLOWED_METHODS')`, if that return True, then `allowed_methods` must be used, otherwise `method_whitelist`.

Also meanwhile found out that it works with urllib 1.24.x and 1.25.x when using `method_whitelist`.

Another problem can occur when the requests module is too old, eg. with 2.14.2 got this:

```
Fatal error: python3-fd-mod: Unexpected Error retrieving NVRAM file: unsupported operand type(s) for -=: 'Retry' and 'int'
```

But it works with requests version 2.20.x
